Added update checker

diff --git a/rshred b/rshred
--- a/rshred
+++ b/rshred
@@ -107,6 +107,9 @@ loadconf() {
                 RemoveDirectories)
                                   rmvdir="$value"
                       ;;
+                CheckForUpdates)
+                                checkupdates="$value"
+                      ;;
             esac
         fi
         if [[ "$line" =~ ^ExcludedDirectories[[:space:]]*\<\<[[:space:]]*(.*)$ ]]; then
@@ -135,6 +138,10 @@ if [[ ! -f $conffile ]]; then
     read confcreate
     if [[ ! $confcreate == n && ! $confcreate == N ]]; then
         mkdir -p $confpath
+        echo "# Checks for updates on boot. (ON/OFF) Default: OFF" >> $conffile
+        echo "" >> $conffile
+        echo "CheckForUpdates=OFF" >> $conffile
+        echo "" >> $conffile
         echo "# Disables creation of temp files alltogether. Will disable functionality for recursive permission checking, error detection, and error counting. (ON/OFF) Default: OFF" >> $conffile
         echo "" >> $conffile
         echo "NoTemp=OFF" >> $conffile
@@ -251,7 +258,16 @@ if [[ $confexist == 1 ]]; then
     echo ""
     echo "Configuration file located at $conffile."
 fi
+
 echo "Welcome to rshred $rversion! Please enter the file/directory you would like to shred."
+if [[ $checkupdates == "ON" ]]; then
+    lateststable="$(curl -fsSL https://codeberg.org/TrollgeEngineering/rshred/raw/branch/main/version.txt)"
+    if [[ $? != 0 ]]; then
+        echo "ERROR: failed to check for updates."
+    elif [[ $rversion != $lateststable ]]; then
+        echo "Version $lateststable of rshred is available! Get it at https://codeberg.org/TrollgeEngineering/rshred"
+    fi
+fi
 read -r shredvictim
 if [ ! -e "$shredvictim" ]; then
     echo ""
